
//! Autogenerated weights for `pallet_session_validator_management`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-04-17, STEPS: `500`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `m-83jm`, CPU: `AMD Ryzen 9 8945HS w/ Radeon 780M Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/midnight-node-runtime/midnight_node_runtime.wasm
// --genesis-builder=spec
// --wasm-execution=compiled
// --pallet=pallet_session_validator_management
// --extrinsic=*
// --steps
// 500
// --repeat
// 20
// --output
// partner-chains/toolkit/committee-selection/pallet/src/weights.rs
// --template=./res/weights-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_session_validator_management`.
pub trait WeightInfo {
	fn set(v: u32, ) -> Weight;
	fn set_main_chain_scripts() -> Weight;
}

/// Weights for `pallet_session_validator_management` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SessionCommitteeManagement::CurrentCommittee` (r:1 w:0)
	/// Proof: `SessionCommitteeManagement::CurrentCommittee` (`max_values`: Some(1), `max_size`: Some(1300010), added: 1300505, mode: `MaxEncodedLen`)
	/// Storage: `SessionCommitteeManagement::NextCommittee` (r:1 w:1)
	/// Proof: `SessionCommitteeManagement::NextCommittee` (`max_values`: Some(1), `max_size`: Some(1300010), added: 1300505, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[0, 10000]`.
	fn set(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `213`
		//  Estimated: `1301495`
		// Minimum execution time: 11_091_000 picoseconds.
		Weight::from_parts(11_672_000, 1301495)
			// Standard Error: 96
			.saturating_add(Weight::from_parts(115_124, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `SessionCommitteeManagement::MainChainScriptsConfiguration` (r:0 w:1)
	/// Proof: `SessionCommitteeManagement::MainChainScriptsConfiguration` (`max_values`: Some(1), `max_size`: Some(178), added: 673, mode: `MaxEncodedLen`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_635_000 picoseconds.
		Weight::from_parts(3_066_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `SessionCommitteeManagement::CurrentCommittee` (r:1 w:0)
	/// Proof: `SessionCommitteeManagement::CurrentCommittee` (`max_values`: Some(1), `max_size`: Some(1300010), added: 1300505, mode: `MaxEncodedLen`)
	/// Storage: `SessionCommitteeManagement::NextCommittee` (r:1 w:1)
	/// Proof: `SessionCommitteeManagement::NextCommittee` (`max_values`: Some(1), `max_size`: Some(1300010), added: 1300505, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[0, 10000]`.
	fn set(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `213`
		//  Estimated: `1301495`
		// Minimum execution time: 11_091_000 picoseconds.
		Weight::from_parts(11_672_000, 1301495)
			// Standard Error: 96
			.saturating_add(Weight::from_parts(115_124, 0).saturating_mul(v.into()))
			.saturating_add(ParityDbWeight::get().reads(2_u64))
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `SessionCommitteeManagement::MainChainScriptsConfiguration` (r:0 w:1)
	/// Proof: `SessionCommitteeManagement::MainChainScriptsConfiguration` (`max_values`: Some(1), `max_size`: Some(178), added: 673, mode: `MaxEncodedLen`)
	fn set_main_chain_scripts() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_635_000 picoseconds.
		Weight::from_parts(3_066_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
}
