
//! Autogenerated weights for `pallet_federated_authority_observation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-04-17, STEPS: `500`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `m-83jm`, CPU: `AMD Ryzen 9 8945HS w/ Radeon 780M Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/midnight-node-runtime/midnight_node_runtime.wasm
// --genesis-builder=spec
// --wasm-execution=compiled
// --pallet=pallet_federated_authority_observation
// --extrinsic=set_council_address,set_technical_committee_address,set_council_policy_id,set_technical_committee_policy_id
// --steps
// 500
// --repeat
// 20
// --output
// pallets/federated-authority-observation/src/weights.rs
// --template=./res/weights-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_federated_authority_observation`.
pub trait WeightInfo {
	fn set_council_address() -> Weight;
	fn set_technical_committee_address() -> Weight;
	fn set_council_policy_id() -> Weight;
	fn set_technical_committee_policy_id() -> Weight;
}

/// Weights for `pallet_federated_authority_observation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `FederatedAuthorityObservation::MainChainCouncilAddress` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainCouncilAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_council_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_815_000 picoseconds.
		Weight::from_parts(3_306_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainTechnicalCommitteeAddress` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainTechnicalCommitteeAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_technical_committee_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_805_000 picoseconds.
		Weight::from_parts(3_256_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainCouncilPolicyId` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainCouncilPolicyId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_council_policy_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_545_000 picoseconds.
		Weight::from_parts(2_906_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainTechnicalCommitteePolicyId` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainTechnicalCommitteePolicyId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_technical_committee_policy_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_515_000 picoseconds.
		Weight::from_parts(2_946_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `FederatedAuthorityObservation::MainChainCouncilAddress` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainCouncilAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_council_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_815_000 picoseconds.
		Weight::from_parts(3_306_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainTechnicalCommitteeAddress` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainTechnicalCommitteeAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_technical_committee_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_805_000 picoseconds.
		Weight::from_parts(3_256_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainCouncilPolicyId` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainCouncilPolicyId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_council_policy_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_545_000 picoseconds.
		Weight::from_parts(2_906_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `FederatedAuthorityObservation::MainChainTechnicalCommitteePolicyId` (r:0 w:1)
	/// Proof: `FederatedAuthorityObservation::MainChainTechnicalCommitteePolicyId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_technical_committee_policy_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_515_000 picoseconds.
		Weight::from_parts(2_946_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
}
