// This file is part of midnight-node.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

mod utils;

pub use utils::find_dependency_version;

#[path = "versions"]
pub mod hard_fork_test {
	pub use {
		base_crypto_hf as base_crypto, coin_structure_hf as coin_structure,
		ledger_storage_hf as ledger_storage, midnight_serialize_hf as midnight_serialize,
		mn_ledger_hf as mn_ledger, onchain_runtime_hf as onchain_runtime,
		transient_crypto_hf as transient_crypto, zkir_hf as zkir, zswap_hf as zswap,
	};

	#[allow(clippy::duplicate_mod)]
	mod common;
	pub use common::*;
}

#[path = "versions"]
pub mod latest {
	pub use {
		base_crypto, coin_structure, ledger_storage, midnight_serialize, mn_ledger,
		onchain_runtime, transient_crypto, zkir, zswap,
	};

	#[allow(clippy::duplicate_mod)]
	mod common;
	pub use common::*;
}

#[cfg(hardfork_test)]
pub use hard_fork_test::*;

#[cfg(not(hardfork_test))]
pub use latest::*;

#[cfg(test)]
mod state_root_tests {
	use crate::latest::{
		BlockContext, DefaultDB, LedgerState, NormalizedCost, ProofMarker, PureGeneratorPedersen,
		Signature, Transaction, compute_overall_fullness, context::LedgerContext, deserialize,
	};
	use hex::encode as hex_encode;
	use std::io::Cursor;

	/// Test to reproduce intermittent state root mismatch.
	/// Requires test data in /tmp/state_mismatch/ (generated by running toolkit against qanet).
	///
	/// Run with: cargo test -p midnight-node-ledger-helpers --features can-panic test_state_root -- --nocapture
	#[test]
	fn test_state_root_determinism_pre_block() {
		use std::fs;

		let dir = "../../state_mismatch";
		let state_path = format!("{dir}/pre_block_state.bin");

		if !std::path::Path::new(&state_path).exists() {
			println!("Skipping test: {state_path} not found. Run toolkit to generate test data.");
			return;
		}

		// Load pre-block state
		let state_bytes = fs::read(&state_path).expect("Failed to read pre_block_state.bin");
		let ledger_state: LedgerState<DefaultDB> =
			deserialize(Cursor::new(&state_bytes)).expect("Failed to deserialize ledger state");

		// Compute state root multiple times to check for non-determinism
		let iterations = 100;
		let mut roots: Vec<Vec<u8>> = Vec::with_capacity(iterations);

		for i in 0..iterations {
			let root = LedgerContext::<DefaultDB>::compute_state_root(&ledger_state)
				.expect("Failed to compute state root");
			roots.push(root);

			if i > 0 && roots[i] != roots[0] {
				println!(
					"NON-DETERMINISM DETECTED at iteration {i}!\n  First:   {}\n  Current: {}",
					hex_encode(&roots[0]),
					hex_encode(&roots[i])
				);
			}
		}

		// Check all roots are identical
		let first_root = &roots[0];
		let all_same = roots.iter().all(|r| r == first_root);

		if all_same {
			println!(
				"Pre-block: All {iterations} state root computations were identical: {}",
				hex_encode(first_root)
			);
		} else {
			let unique_roots: std::collections::HashSet<_> = roots.iter().collect();
			println!("Found {} unique roots out of {iterations} computations:", unique_roots.len());
			for (i, root) in unique_roots.iter().enumerate() {
				let count = roots.iter().filter(|r| *r == *root).count();
				println!("  Root {i}: {} (appeared {count} times)", hex_encode(root));
			}
			panic!("Pre-block state root computation is non-deterministic!");
		}
	}

	/// Test applying transaction and computing post-block state root.
	#[test]
	fn test_state_root_determinism_post_tx() {
		use crate::latest::{TransactionContext, WellFormedStrictness};
		use std::fs;

		let dir = "../../state_mismatch";
		let state_path = format!("{dir}/pre_block_state.bin");
		let tx_path = format!("{dir}/tx_0.bin");
		let ctx_path = format!("{dir}/block_context.bin");

		if !std::path::Path::new(&state_path).exists() {
			println!("Skipping test: {state_path} not found. Run toolkit to generate test data.");
			return;
		}

		// Load test data
		let state_bytes = fs::read(&state_path).expect("Failed to read pre_block_state.bin");
		let tx_bytes = fs::read(&tx_path).expect("Failed to read tx_0.bin");
		let ctx_bytes = fs::read(&ctx_path).expect("Failed to read block_context.bin");

		let pre_state: LedgerState<DefaultDB> =
			deserialize(Cursor::new(&state_bytes)).expect("Failed to deserialize ledger state");
		let tx: Transaction<Signature, ProofMarker, PureGeneratorPedersen, DefaultDB> =
			deserialize(Cursor::new(&tx_bytes)).expect("Failed to deserialize transaction");
		let block_context: BlockContext =
			deserialize(Cursor::new(&ctx_bytes)).expect("Failed to deserialize block context");

		println!("Loaded test data:");
		println!("  Block timestamp: {}", block_context.tblock.to_secs());
		println!("  Parent hash: {}", hex_encode(block_context.parent_block_hash.0));

		// Apply transaction and post_block_update multiple times, compute state root each time
		let iterations = 20;
		let mut roots: Vec<Vec<u8>> = Vec::with_capacity(iterations);

		for i in 0..iterations {
			// Clone state for this iteration
			let mut state = pre_state.clone();

			// Create transaction context
			let tx_context = TransactionContext {
				ref_state: state.clone(),
				block_context: block_context.clone(),
				whitelist: None,
			};

			// Validate and apply transaction
			let strictness: WellFormedStrictness = Default::default();
			let valid_tx = tx
				.well_formed(&tx_context.ref_state, strictness, block_context.tblock)
				.expect("Transaction validation failed");

			let (new_state, _result) = tx_context.ref_state.apply(&valid_tx, &tx_context);
			state = new_state;

			// Apply post_block_update
			let normalized_fullness = NormalizedCost::ZERO;
			let overall_fullness = compute_overall_fullness(&normalized_fullness);

			state = state
				.post_block_update(block_context.tblock, normalized_fullness, overall_fullness)
				.expect("Failed to apply post_block_update");

			// Compute state root
			let root = LedgerContext::<DefaultDB>::compute_state_root(&state)
				.expect("Failed to compute state root");

			if i > 0 && roots.first().map(|r| r != &root).unwrap_or(false) {
				println!(
					"NON-DETERMINISM DETECTED at iteration {i}!\n  First:   {}\n  Current: {}",
					hex_encode(&roots[0]),
					hex_encode(&root)
				);
			}
			roots.push(root);
		}

		// Check all roots are identical
		let first_root = &roots[0];
		let all_same = roots.iter().all(|r| r == first_root);

		if all_same {
			println!(
				"Post-tx: All {iterations} state root computations were identical: {}",
				hex_encode(first_root)
			);
		} else {
			let unique_roots: std::collections::HashSet<_> = roots.iter().collect();
			println!("Found {} unique roots out of {iterations} computations:", unique_roots.len());
			for (i, root) in unique_roots.iter().enumerate() {
				let count = roots.iter().filter(|r| *r == *root).count();
				println!("  Root {i}: {} (appeared {count} times)", hex_encode(root));
			}
			panic!("Post-tx state root computation is non-deterministic!");
		}
	}
}
